# Generated by Django 6.0.7 on 2026-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_masterprofile_avatar_masterprofile_logo_workphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
